### PR TITLE
Some changes in program UI

### PR DESCRIPTION
**Pull request by polahano**
# Description

I've made some changes in program UI like:
- Adding ImageLab new logo.
- Adding ScoreLab logo on the interface.
- Changing buttons to rounded ages
- Edited read me file by removing repeated information.
- Removed checkstyle dependency because it gives errors while building the program (I am not sure if it these errors are my mistake or it really shows these errors for all)

That's my first contribution and I wish could be useful and I will continue to contribute to that amazing project by enhancing user experience of the program and by adding new functionalities.

Greetings,
Pola

### CODE REVIEW

**Comment by polahano** [comment]
Screenshot 2021-04-02 175028

**Comment by ivantha** [comment]
Please break these down into separate PRs. 
```
Adding ImageLab new logo.
Adding ScoreLab logo on the interface.
Changing buttons to rounded ages
Edited read me file by removing repeated information.
Removed checkstyle dependency because it gives errors while building the program (I am not sure if it these errors are my mistake or it really shows these errors for all)
```

**Review by ivantha — CHANGES_REQUESTED** [review]
Break down into separate PRs.

**Comment by polahano** [comment]
Sure, I will

**Pull request closed without merging**
