### PR TITLE
Npm install bug fix

### LINKED ISSUE #121: Fix dependency issue
When installing the packages a dependency issue occur. Try to fix the issue by changing the dependency versions.

Screenshot 2023-02-23 at 23 49 06

### PR DESCRIPTION
**Pull request by Malith-19**
# Description

npm, install issue solved. It occurs by the custom-electron-titlebar node package. I changed to a corrected version and now all are working.
- Fixes #121 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- [x] ran npm i
- [x] ran npm install
- [x] verified the functionalities of the electron app 

Also, include screenshots for verification and reviewing purpose.
image

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by kaveeshadinamidu** [comment]
@Malith-19 did the view affected by the package upgrade?

**Comment by Malith-19** [comment]
> @Malith-19 did the view affected by the package upgrade?

I think yes. New version replacing some older properties I think.

**Comment by ghost** [comment]
i wanna work on this issue

**Comment by kaveeshadinamidu** [comment]
@Malith-19 Can you attach some screenshots of the new view?

**Comment by Malith-19** [comment]
image

image

image

**Comment by Malith-19** [comment]
image

**Review by kaveeshadinamidu — APPROVED** [review]

**Review by kaveeshadinamidu — APPROVED** [review]

**Comment by SahanDisa** [comment]
@kaveeshadinamidu is this PR good to merge?

**Review by SahanDisa — APPROVED** [review]

**Pull request merged**
