### PR TITLE
Improved tooltip message and added help url for the operators

### PR DESCRIPTION
**Pull request by abdullahranginwala**
# Description
I have changed the tooltip message of several operators to become more descriptive and comprehensive. Along with that, I have added helpURL as well.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Manually tested

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by impragya08** [comment]
Hello @abdullahranginwala, I wanted to let you know that I have reviewed your pull request and overall, I think the work looks great. However, I noticed that there are still a few small grammatical and typographical errors that remain. Would you mind reviewing and addressing these issues? Alternatively, if you are open to it, I would be happy to contribute to the PR to help ensure its quality.

**Comment by abdullahranginwala** [comment]
Absolutely! Feel free to contribute to the PR, I'll also go through the changes once again.

**Review by SahanDisa — APPROVED** [review]

**Comment by SahanDisa** [comment]
I think I can safely close this PR since @impragya08 corrected it in #148

**Review by SahanDisa — APPROVED** [review]

**Comment by SahanDisa** [comment]
Close this PR due to #148 includes the fix

**Pull request closed without merging**
