### PR TITLE
Templates

### LINKED ISSUE #42: Need issue and pull request templates
The following templates are required

1. PR Template
2. Issues - Bug Report
3. Issues - Feature Request

### PR DESCRIPTION
**Pull request by viraj-dhanushka**
This PR closes #42

### CODE REVIEW

**Review by ivantha — APPROVED** [review]

**Comment by ivantha** [comment]
@viradhanus Can you please remove the PR template? We can merge the rest. 
Sorry I merged some PR ahead of this and it had a PR template.

**Comment by viraj-dhanushka** [comment]
@ivantha done :+1:

**Comment by ivantha** [comment]
Please rebase the PR.

**Comment by viraj-dhanushka** [comment]
@ivantha done :+1:

**Pull request closed without merging**
